[package]
name = "xmlparse_native"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "xmlparse_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
libxml = "0.2.15"
